trigger:
  branches:
    include:
      - main
  paths:
    include:
      - register/**  

variables:
  vmImage: 'ubuntu-latest'
  azureSubscription: 'azure-devops-sp'  # Service connection do Azure Resource Manager
  acrConnection: 'cyco-acr-connection'  # Nome da service connection do Docker Registry (ACR)
  acrName: 'cycocontainerregistry.azurecr.io'  # URL do ACR (usada apenas para referência)
  appServiceName: 'cyco'       # Nome do App Service
  resourceGroup: 'cyco-dev'     # Grupo de recursos
  serviceName: 'register'       # Nome do serviço

stages:
  - stage: Build_and_Push_Image
    displayName: Build e Push da Imagem
    jobs:
      - job: Build
        displayName: Build Docker Image
        pool:
          vmImage: $(vmImage)
        steps:
          - checkout: self

          # Login no ACR usando a service connection do Docker Registry
          - task: Docker@2
            displayName: Login no ACR
            inputs:
              command: login
              containerRegistry: $(acrConnection)  # Nome da service connection!

          # Build da imagem Docker
          - task: Docker@2
            displayName: Build da Imagem
            inputs:
              command: build
              repository: $(serviceName)
              dockerfile: $(serviceName)/Dockerfile
              tags: |
                $(Build.BuildId)
                latest

          # Push da imagem para o ACR
          - task: Docker@2
            displayName: Push para o ACR
            inputs:
              command: push
              repository: $(serviceName)
              tags: |
                $(Build.BuildId)
                latest

  - stage: Deploy_to_App_Service
    displayName: Deploy no App Service  
    dependsOn: Build_and_Push_Image
    jobs:
      - job: Deploy
        displayName: Deploy no Azure
        pool:
          vmImage: $(vmImage)
        steps:
          # Atualiza o App Service para usar a nova imagem
          - task: AzureWebAppContainer@1
            displayName: Deploy no App Service
            inputs:
              azureSubscription: $(azureSubscription)  # Service connection do Azure Resource Manager
              appName: $(appServiceName)
              resourceGroupName: $(resourceGroup)
              containerRegistry: $(acrConnection)  # Nome da service connection do Docker Registry
              repository: $(serviceName)
              tag: $(Build.BuildId)
