trigger:
  branches:
    include:
      - main
  paths:
    include:
      - register/**  

variables:
  azureSubscription: 'azure-devops-sp'
  acrConnection: 'cyco-acr-connection'
  acrName: 'cycocontainerregistry.azurecr.io'
  appServiceName: 'cyco'
  resourceGroup: 'cyco-dev'
  serviceName: 'register'

stages:
  - stage: Build_Deploy
    displayName: Build e Deploy
    jobs:
      - job: Single_Job
        displayName: Único Job
        pool: Default  # Usa self-hosted agent
        steps:
          - checkout: self

          # Login no ACR
          - task: Docker@2
            displayName: Login no ACR
            inputs:
              command: login
              containerRegistry: $(acrConnection)

          # Build da imagem
          - task: Docker@2
            displayName: Build da Imagem
            inputs:
              command: build
              repository: $(serviceName)
              dockerfile: $(serviceName)/Dockerfile
              tags: |
                $(Build.BuildId)
                latest

          # Push para o ACR
          - task: Docker@2
            displayName: Push para o ACR
            inputs:
              command: push
              repository: $(serviceName)
              tags: |
                $(Build.BuildId)
                latest

          # Deploy no App Service
          - task: AzureWebAppContainer@1
            displayName: Deploy no App Service
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(appServiceName)
              resourceGroupName: $(resourceGroup)
              containerRegistry: $(acrConnection)
              repository: $(serviceName)
              tag: $(Build.BuildId)
