trigger:
  branches:
    include:
      - main
  paths:
    include:
      - register/**  

variables:
  vmImage: 'ubuntu-latest'
  azureSubscription: 'azure-devops-sp'  # Service connection do Azure Resource Manager
  acrConnection: 'cyco-acr-connection'  # Nome da service connection do Docker Registry (ACR)
  acrName: 'cycocontainerregistry.azurecr.io'  # URL do ACR
  appServiceName: 'cyco'       # Nome do App Service
  resourceGroup: 'cyco-dev'     # Grupo de recursos
  serviceName: 'register'       # Nome do serviço

stages:
  - stage: Build_Deploy
    displayName: Build e Deploy
    jobs:
      - job: Build_and_Deploy_Job
        displayName: Build e Deploy
        pool:
          vmImage: $(vmImage)
        steps:
          # Checkout do código
          - checkout: self

          # Login no ACR
          - task: Docker@2
            displayName: Login no ACR
            inputs:
              command: login
              containerRegistry: $(acrConnection)

          # Build da imagem Docker
          - task: Docker@2
            displayName: Build da Imagem
            inputs:
              command: build
              repository: $(serviceName)
              dockerfile: $(serviceName)/Dockerfile
              tags: |
                $(Build.BuildId)
                latest

          # Push da imagem para o ACR
          - task: Docker@2
            displayName: Push para o ACR
            inputs:
              command: push
              repository: $(serviceName)
              tags: |
                $(Build.BuildId)
                latest

          # Deploy no App Service
          - task: AzureWebAppContainer@1
            displayName: Deploy no App Service
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(appServiceName)
              resourceGroupName: $(resourceGroup)
              containerRegistry: $(acrConnection)
              repository: $(serviceName)
              tag: $(Build.BuildId)
