POST http://localhost:3000/generator
Content-Type: application/json

{
  "email": "lidia1@gmail.com",
  "password": "lidia123456",
  "birthDate": "2015-03-25T00:00:00.000Z",
  "document": "47189168877",
  "name": "Lídia Galdino 4",
  "phone": {
    "ddd": 11,
    "ddi": 55,
    "number": 961869684
  }
}

###
GET http://localhost:3000/generator/fe875bd7-1674-4e8d-a27a-e2c03f3c814a

###
POST http://localhost:3000/generator/fe875bd7-1674-4e8d-a27a-e2c03f3c814a/address
Content-Type: application/json

{
  "zipCode": "06449301",
    "complement": "124B",
    "number": "930"
}
